# Generated by Django 5.0.4 on 2024-05-07 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dividends', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dividens',
            old_name='procent_of_dividends',
            new_name='percent_of_dividends',
        ),
    ]
